name: Build CI

on:
  push:
  pull_request:
  release:
    types: [published]
  check_suite:
    types: [rerequested]

jobs:
  build-arm:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        board:
        - "nucleo_f746zg"
        - "trinket_m0"
    steps:
      - name: Cache gcc-arm
        uses: actions/cache@v1.0.3
        id: cache-gcc-arm
        with:
            path: "~/local"
            key: ${{ runner.os }}-build-${{ env.cache-name }}
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install deps
        run: |
          sudo apt-get install -y gettext
          pip install requests sh click setuptools awscli
          wget https://adafruit-circuit-python.s3.amazonaws.com/gcc-arm-none-eabi-9-2019-q4-major-x86_64-linux.tar.bz2
          sudo tar -C ~/local --strip-components=1 -xaf gcc-arm-none-eabi-9-2019-q4-major-x86_64-linux.tar.bz2
        if: steps.cache-gcc-arm.outputs.cache-hit != 'true'
      - name: Versions
        run: |
          gcc --version
          arm-none-eabi-gcc --version
          python3 --version
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0
      - run: git fetch --recurse-submodules=no https://github.com/adafruit/circuitpython refs/tags/*:refs/tags/*
      - run: git submodule sync
      - run: git submodule foreach git remote -v
      - run: git submodule foreach git fetch --recurse-submodules=no origin +refs/tags/*:refs/tags/*
      - name: mpy-cross
        run: make -C mpy-cross -j2
      - name: build
        run: python3 -u build_release_files.py
        working-directory: tools
        env:
          BOARDS: ${{ matrix.board }}
